### ISSUE TITLE
CertFindCertificateInStore() failed with: Cannot find object or property

### ISSUE THREAD

**Issue by bojeil-google** [mongodb-js/win-export-certificate-and-key#6]
When using `exportCertificateAndPrivateKey`, I am running into the following error `Error: CertFindCertificateInStore() failed with: Cannot find object or property, (0x80092004)` on some windows machines (it works on my local machine). I am not sure why.

Any clues why this may be happening?

<img width="1557" alt="Screenshot 2024-07-11 at 10 42 53 AM" src="https://github.com/mongodb-js/win-export-certificate-and-key/assets/13474811/91fc92be-4efd-4f2e-8a0e-bb98ebcd6f40">

Note I am using [`pkg`](https://www.npmjs.com/package/pkg) to package my app into a single executable.

**Comment by bojeil-google** [comment]
Never mind. This seems to be the error when the cert is not found.

**Comment by addaleax** [comment]
@bojeil-google Yes, that sounds about right – the error is coming from Windows itself in this case. Let us know if you run into anything else!
